/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.luxbus.frontend;

import de.frauas.luxbus.backend.DBHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.validator.routines.EmailValidator;


public class CodegeneratorForAdmin extends javax.swing.JFrame {
    /**
     * Creates new form CodegeneratorForAdmin
     */
    public CodegeneratorForAdmin() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        halloAdminLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        euroLabel = new javax.swing.JLabel();
        euroTextField = new javax.swing.JTextField();
        mailLabel = new javax.swing.JLabel();
        mailTextField = new javax.swing.JTextField();
        generateCouponButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("generate new coupon");

        halloAdminLabel.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        halloAdminLabel.setText("Hallo Admin");

        infoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        infoLabel.setText("Each one Luxcoin is equal one euro € !");

        euroLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        euroLabel.setText("please Enter the paying amount in euro € in the field:");

        euroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euroTextFieldActionPerformed(evt);
            }
        });

        mailLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mailLabel.setText("Please enter the email address of the person in the field:");

        mailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailTextFieldActionPerformed(evt);
            }
        });

        generateCouponButton.setText("Generate coupons");
        generateCouponButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateCouponButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(halloAdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(infoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(euroLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(euroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(generateCouponButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(halloAdminLabel)
                .addGap(18, 18, 18)
                .addComponent(infoLabel)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(euroLabel)
                    .addComponent(euroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailLabel))
                .addGap(18, 18, 18)
                .addComponent(generateCouponButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void euroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euroTextFieldActionPerformed
        
        
    }//GEN-LAST:event_euroTextFieldActionPerformed

    private void mailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailTextFieldActionPerformed

    private void generateCouponButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateCouponButtonActionPerformed
        final int n = 10;
        String code = RGenerator.coupon(n);
        String mail = mailTextField.getText();
        double codep = 0;
        try
        {
            codep = Double.parseDouble(euroTextField.getText());
            // Valid double
        }
        catch (NullPointerException | NumberFormatException ex)
        {
        // Not valid double
        }
        // Euro String is Numeric and not text 
        // Check Email (Validate or not)
        boolean isNumeric = StringUtils.isNumeric(euroTextField.getText());
        boolean Validate= EmailValidator.getInstance().isValid(mail);
        if (!isNumeric){
            JOptionPane.showMessageDialog(null,"please enter a valide Euro-number","ERROR", JOptionPane.ERROR_MESSAGE);
        }else if(euroTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"please enter a valide Euro-number","ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else if( Validate== false || mail.isEmpty())
        {
              JOptionPane.showMessageDialog(null, "Please enter a valid E-Mail address!","ERROR", JOptionPane.ERROR_MESSAGE); 
        }
        else{
            DBHandler db = new DBHandler();
            int i = 1;
            db.paymentCoupons(code, codep, mail,i);
            JOptionPane.showMessageDialog(null,"Successfully created");
            System.out.println(codep);
            String subject = "Your Luxcoin Code";
            String info = "Hello\nnice that you use Luxpayment and grab the opportunity to buy tickets cheap and invest in Luxcoin at the same time.\n\n\n You can top up your account with the code:  " +code+"\n\nwe wish you a good day\n\n LuxBus";
            SendEMail send = new SendEMail();
            String newinfo = "\n\n\n\n";
            try {
                send.sendMail(mail, info,newinfo, subject, null);
            }catch (Exception ex) {
                Logger.getLogger(CodegeneratorForAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
        }
        
    }//GEN-LAST:event_generateCouponButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel euroLabel;
    private javax.swing.JTextField euroTextField;
    private javax.swing.JButton generateCouponButton;
    private javax.swing.JLabel halloAdminLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField mailTextField;
    // End of variables declaration//GEN-END:variables

    
}
