/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.luxbus.frontend;

import de.frauas.luxbus.backend.DBHandler;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author haith
 */
public class GiveCouponUser extends javax.swing.JFrame {
    String username;
    /**
     * Creates new form GiveCouponUser
     * @param username
     */
    public GiveCouponUser(String username) {
        this.username=username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tenDigitLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        tenDigitTextFieled = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Coupon Luxcoin");

        tenDigitLabel.setText("Give your ten-digit code here:");

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        tenDigitTextFieled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenDigitTextFieledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tenDigitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenDigitTextFieled, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenDigitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenDigitTextFieled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(SubmitButton)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenDigitTextFieledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenDigitTextFieledActionPerformed
        
    }//GEN-LAST:event_tenDigitTextFieledActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        int i = 0;
        DBHandler mydbhandler= new DBHandler();
        ResultSet checkSec = mydbhandler.checkcoupons(tenDigitTextFieled.getText());
        if(tenDigitTextFieled.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"please enter a valid Code");
        }
        else if (!mydbhandler.checkstatmentExsist(checkSec))
        {
           JOptionPane.showMessageDialog(null,"the code dose not exists or it was used");
        }
        else {
            try {
                price = mydbhandler.SelectPrice("Price", "codep", tenDigitTextFieled.getText()); 
            } catch (SQLException ex) {
                Logger.getLogger(GiveCouponUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            double amount = Double.parseDouble(price);
            String currentamount = null;
            String lastprice = null;
            try {
                currentamount = mydbhandler.SelectPriceFromUsers("currentp", "usernamep", username);
            } catch (SQLException ex) {
                Logger.getLogger(GiveCouponUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            double currentAmount2 = Double.parseDouble(currentamount);
            currentAmount2 += amount;
            lastprice = Double.toString(currentAmount2);
            mydbhandler.UpdatePayment2("currentp", lastprice, username);
            mydbhandler.Updatecoupon(tenDigitTextFieled.getText());
            DateAndTime dANDt = new DateAndTime();
            String date = dANDt.getDate();
            String time = dANDt.getTime();
            String sentOrReceived = "Received";
            String sentTo = "----";
            String received = "Coupoun code";
            
            
            System.out.println("Username "+username+"\ndate ======> "+date+"\ntime ======>"+ time);
            mydbhandler.insertUserstoryP(username, sentOrReceived, sentTo, received, amount, date, time);
            JOptionPane.showMessageDialog(null,"please login with your payment to see the current status");
        }
            dispose();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton SubmitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tenDigitLabel;
    public javax.swing.JTextField tenDigitTextFieled;
    // End of variables declaration//GEN-END:variables

    String price;
}
