/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.luxbus.frontend;

import de.frauas.luxbus.backend.DBHandler;
import de.frauas.luxbus.backend.Encryption;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author haith
 */
public class LastBook extends javax.swing.JFrame {
    int id;
String fromcity;
String tocity;
String Datum;
String departureTime;
String arriveTime;
double price;
int seat;
int seatdb;
String username="Gast";
ButtonGroup gengp=new ButtonGroup(); 
    /**
     * Creates new form LastBook
     */

    public LastBook(int id ,String fromcity, String tocity, String Datum, String departureTime, String arriveTime, double price,int seat, int seatdb) {
        this.id=id;
        this.fromcity=fromcity;
        this.tocity=tocity;
        this.Datum=Datum;
        this.departureTime=departureTime;
        this.arriveTime=arriveTime;
        this.price = price;
        this.seat=seat;
        this.seatdb=seatdb;
        initComponents();
    }

   
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spotCheckBox = new javax.swing.JCheckBox();
        luxcoinCheckBox = new javax.swing.JCheckBox();
        nextButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordField1 = new javax.swing.JPasswordField();
        usernemeTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usernemeTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choosen payment method");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Please select a payment method to confirm your trip ");

        gengp.add(spotCheckBox);
        spotCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spotCheckBox.setText("pay before departure");
        spotCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spotCheckBoxActionPerformed(evt);
            }
        });

        gengp.add(luxcoinCheckBox);
        luxcoinCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        luxcoinCheckBox.setText("pay with Luxcoin");

        nextButton.setText("Next ");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Payment username ");

        jLabel3.setText("Payment password");

        passwordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordField1ActionPerformed(evt);
            }
        });

        usernemeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernemeTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText(""+price+" €");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Amount payable:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Create an account by luxcoin");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setText("Give your E-Mail address");

        usernemeTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernemeTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(luxcoinCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(usernemeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(passwordField1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(usernemeTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(spotCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luxcoinCheckBox)
                    .addComponent(spotCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernemeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernemeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addComponent(nextButton)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spotCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spotCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spotCheckBoxActionPerformed

    private void passwordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField1ActionPerformed
    
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (luxcoinCheckBox.isSelected()){
            String username = usernemeTextField.getText();
             String pw = passwordField1.getText();
            Encryption enc = new Encryption(pw);
            String hash= enc.HaschCode();
            DBHandler mydbhandler= new DBHandler();
            ResultSet checkSec= mydbhandler.SelectData2colmn("paymentUsers", "usernamep", "passwordp",username,hash);
            String currentamount = null;
            
            if(usernemeTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"please enter a valid Username");
            }
            else if(passwordField1.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"please enter a valid password");
            }
            else if (!mydbhandler.checkstatmentExsist(checkSec))
            {
                JOptionPane.showMessageDialog(null,"Username or password are not correct");
            }
            else {
                try {
                    currentamount = mydbhandler.SelectPriceFromUsers("currentp", "usernamep", username);
                } catch (SQLException ex) {
                    Logger.getLogger(PaymentLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Aktuell amount =======>" + currentamount);
                double currentamoun2 = Double.parseDouble(currentamount);
                currentamoun2 -= price;
                if (currentamoun2 < 0){
                JOptionPane.showMessageDialog(null,"not available your balances are not sufficient");
                }
                else{
                String newCurrentamount = Double.toString(currentamoun2);
                mydbhandler.UpdatePayment2("currentp", newCurrentamount, username);
                System.out.println("Done alright");
                DateAndTime dANDt = new DateAndTime();
                String date = dANDt.getDate();
                String time = dANDt.getTime();
                String sentOrReceived = "Received for Tiket";
                String sentTo = "----";
                String received = "Luxpayment";
            
                System.out.println("Username "+username+"\ndate ======> "+date+"\ntime ======>"+ time);
                mydbhandler.insertUserstoryP(username, sentOrReceived, sentTo, received, price, date, time);
     //           mydbhandler.insertUserstoryT(username, fromcity, tocity, Datum, departureTime, arriveTime, price,seat);
            
            JOptionPane.showMessageDialog(null,"please login with your payment to see the current status");
            
            String nachricht = "thank you for your booking , here below you can see the booking information.\n\n";
                String info7 = "\n\nplease bring a negative covid-19 and be there about 10 minutes early\n\n";
                ExportPDF export = new ExportPDF();
                export.pdfExport(username, date, nachricht, "From : "+fromcity, "To : " + tocity, "Date : " + date, "Departure time : " +departureTime, "Arrive time : " + arriveTime, "Price : " + price, info7);
                String path = "d:/" + username + date + ".pdf";
                String subject = "Your Ticket";
                String info = "Hello\nnice that you use Luxpayment and grab the opportunity to buy tickets cheap and invest in Luxcoin at the same time.\n\n\n You see your Ticket information attached with this mail as pdf\n\n\n";
                SendEMail send = new SendEMail();
                String newinfo = "\n\n\n\n";
                String email = null;
                try {
                    email = mydbhandler.SelectemailFromUsers("emailp", "usernamep", username);
                } catch (SQLException ex) {
                    Logger.getLogger(LastBook.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    send.sendMail(email, info,newinfo, subject, path);
                } catch (Exception ex) {
                    Logger.getLogger(LastBook.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Email ===> "+email);
            
                int seattodb=seatdb-seat;
                mydbhandler.inserttravels(  id, seattodb);
                dispose();
                }
            }
        }
        else if(spotCheckBox.isSelected()) {
            
            JOptionPane.showMessageDialog(null,"please be there a little earlier from the departure to be able to pay at service point ");
            JOptionPane.showMessageDialog(null,"successfully reserved, if you are not there before one hour before departure your trip will be disabled ");
            
            DBHandler mydbhandler= new DBHandler();

            
             String nachricht = "Thank you for your booking , here below you can see the booking information.\n\n";
                String info7 = "\n\nplease bring a negative covid-19 and be there about 10 minutes early\n\n";
                ExportPDF export = new ExportPDF();
                export.pdfExport(username, Datum, nachricht, "From : "+fromcity, "To : " + tocity, "Date : " + Datum, "Departure time : " +departureTime, "Arrive time : " + arriveTime, "Price : " + price, info7);
                String path = "d:/" + username + Datum + ".pdf";
                String subject = "Your Ticket";
                String info = "Welcome ,\n" +
                "Thank you for using our service, we wish you a pleasant trip.\n" +
                "Please do not forget to come before so that you can complete your payment.\n\n\n You see your Ticket information attached with this mail as pdf\n\n\n";
                SendEMail send = new SendEMail();
                String newinfo = "\n\n\n\n";
                String email = usernemeTextField1.getText();
                email = usernemeTextField1.getText();
                try {
                    send.sendMail(email, info,newinfo, subject, path);
                } catch (Exception ex) {
                    Logger.getLogger(LastBook.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Email ===> "+email);
            
              int seattodb=seatdb-seat;
                mydbhandler.inserttravels(  id, seattodb);
            dispose();
           
        }
        else {
            JOptionPane.showMessageDialog(null,"please select the Payment method");
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void usernemeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernemeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernemeTextFieldActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new CreateAccountPayment().setVisible(true);;
    }//GEN-LAST:event_jLabel6MouseClicked

    private void usernemeTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernemeTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernemeTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox luxcoinCheckBox;
    private javax.swing.JButton nextButton;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JCheckBox spotCheckBox;
    public javax.swing.JTextField usernemeTextField;
    public javax.swing.JTextField usernemeTextField1;
    // End of variables declaration//GEN-END:variables

  

}
