/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package de.frauas.luxbus.frontend;
import de.frauas.luxbus.backend.DBHandler;
import de.frauas.luxbus.backend.Encryption;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    String username;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LuxBusjLabel1 = new javax.swing.JLabel();
        UsernamejLabel1 = new javax.swing.JLabel();
        UsernamejTextField1 = new javax.swing.JTextField();
        PasswordjLabel1 = new javax.swing.JLabel();
        loginjButton1 = new javax.swing.JButton();
        RegisterjButton1 = new javax.swing.JButton();
        showPassword = new javax.swing.JCheckBox();
        PasswordjTextField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Luxbus Login");

        LuxBusjLabel1.setBackground(new java.awt.Color(0, 255, 102));
        LuxBusjLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        LuxBusjLabel1.setText("LuxBus");

        UsernamejLabel1.setText("Username:");

        UsernamejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamejTextField1ActionPerformed(evt);
            }
        });

        PasswordjLabel1.setText("Password:");

        loginjButton1.setText("login");
        loginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButton1ActionPerformed(evt);
            }
        });

        RegisterjButton1.setText("Register");
        RegisterjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterjButton1ActionPerformed(evt);
            }
        });

        showPassword.setText("show password");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        PasswordjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordjTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UsernamejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LuxBusjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PasswordjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showPassword)
                            .addComponent(PasswordjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(loginjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(LuxBusjLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernamejLabel1)
                    .addComponent(UsernamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordjLabel1)
                    .addComponent(PasswordjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(showPassword)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginjButton1)
                    .addComponent(RegisterjButton1))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernamejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamejTextField1ActionPerformed
        
    }//GEN-LAST:event_UsernamejTextField1ActionPerformed

    private void loginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButton1ActionPerformed
        String pw = PasswordjTextField1.getText();
        Encryption enc = new Encryption(pw);
        String hash= enc.HaschCode();
        
        DBHandler mydbhandler= new DBHandler();
        ResultSet checkSec= mydbhandler.SelectData2colmn("users", "username", "password",UsernamejTextField1.getText(),hash);
        if(UsernamejTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"please enter a valid Username");
        }
        else if(PasswordjTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"please enter a valid password");
        }
        if (!mydbhandler.checkstatmentExsist(checkSec)){
           JOptionPane.showMessageDialog(null,"username or passwor are not correct");
        }
        else {
            user user = mydbhandler.GetUser(UsernamejTextField1.getText());
            if (!user.isAdmin)
            {   
                 username=UsernamejTextField1.getText();
               dispose();
               new StartWindowAfterLogin(username).setVisible(true);
            }
            else {
                  username=UsernamejTextField1.getText();
               dispose();
               new StartWindowAfterLoginAdmin(username).setVisible(true);
            }
        }
    }//GEN-LAST:event_loginjButton1ActionPerformed

    private void RegisterjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterjButton1ActionPerformed
        // TODO add your handling code here:
        
        Register myregister= new Register();
        myregister.setVisible(true);
    }//GEN-LAST:event_RegisterjButton1ActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
       showPassword.isSelected();
       if (evt.getSource() == showPassword) {
            if (showPassword.isSelected()) {
                PasswordjTextField1.setEchoChar((char) 0);
            }
            else {
                PasswordjTextField1.setEchoChar('*');
            } 
         }
       
    }//GEN-LAST:event_showPasswordActionPerformed

    private void PasswordjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordjTextField1ActionPerformed
        
    }//GEN-LAST:event_PasswordjTextField1ActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LuxBusjLabel1;
    private javax.swing.JLabel PasswordjLabel1;
    private javax.swing.JPasswordField PasswordjTextField1;
    private javax.swing.JButton RegisterjButton1;
    private javax.swing.JLabel UsernamejLabel1;
    public javax.swing.JTextField UsernamejTextField1;
    private javax.swing.JButton loginjButton1;
    private javax.swing.JCheckBox showPassword;
    // End of variables declaration//GEN-END:variables

//    private String username = null;
}
