/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.luxbus.frontend;

import de.frauas.luxbus.backend.DBHandler;
import de.frauas.luxbus.backend.Encryption;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.EmailValidator;





/**
 *
 * @author User
 */
public class Register2 extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    String username;
    int id;
    String fromcity;
    String tocity;
    String Datum;
    String departureTime;
    String arriveTime;
    double price;
    int seat;
    int seatdb;
    public Register2(String username,int id ,String fromcity, String tocity, String Datum, String departureTime, String arriveTime, double price,int seat, int seatdb) {
        initComponents();
        this.username=username;
        this.id=id;
        this.fromcity=fromcity;
        this.tocity=tocity;
        this.Datum=Datum;
        this.departureTime=departureTime;
        this.arriveTime=arriveTime;
        this.price=price;
        this.seat=seat;
        this.seatdb=seatdb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstnamejLabel1 = new javax.swing.JLabel();
        FirstnamejTextField1 = new javax.swing.JTextField();
        LastnamejLabel1 = new javax.swing.JLabel();
        LastnamejTextField1 = new javax.swing.JTextField();
        UsernamejLabel1 = new javax.swing.JLabel();
        UsernamejTextField1 = new javax.swing.JTextField();
        RegisterjLabel1 = new javax.swing.JLabel();
        EmailjLabel2 = new javax.swing.JLabel();
        EmailAddressejTextField1 = new javax.swing.JTextField();
        Password1jLabel1 = new javax.swing.JLabel();
        PasswordjLabel2 = new javax.swing.JLabel();
        ConfirmjPasswordField1 = new javax.swing.JPasswordField();
        PasswordjPasswordField2 = new javax.swing.JPasswordField();
        RegisterjButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Luxbus sign up");

        FirstnamejLabel1.setText("First name: ");

        LastnamejLabel1.setText("Last name: ");

        UsernamejLabel1.setText("Username: ");

        RegisterjLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        RegisterjLabel1.setForeground(new java.awt.Color(102, 51, 0));
        RegisterjLabel1.setText("Register");

        EmailjLabel2.setText("Email Addresse: ");

        Password1jLabel1.setText("Password: ");

        PasswordjLabel2.setText("Confirm Password: ");

        ConfirmjPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmjPasswordField1ActionPerformed(evt);
            }
        });

        PasswordjPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordjPasswordField2ActionPerformed(evt);
            }
        });

        RegisterjButton1.setText("Register");
        RegisterjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterjButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Accept Terms And Conditions.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FirstnamejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UsernamejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailjLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Password1jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PasswordjLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LastnamejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FirstnamejTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(LastnamejTextField1)
                                    .addComponent(UsernamejTextField1)
                                    .addComponent(EmailAddressejTextField1)
                                    .addComponent(ConfirmjPasswordField1)
                                    .addComponent(PasswordjPasswordField2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RegisterjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(RegisterjButton1)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterjLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstnamejLabel1)
                    .addComponent(FirstnamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnamejLabel1)
                    .addComponent(LastnamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernamejLabel1)
                    .addComponent(UsernamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EmailjLabel2)
                    .addComponent(EmailAddressejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Password1jLabel1)
                    .addComponent(PasswordjPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordjLabel2)
                    .addComponent(ConfirmjPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterjButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterjButton1ActionPerformed
        // TODO add your handling code here:
        
        EmailAddressejTextField1.getText();
        
        boolean Validate= EmailValidator.getInstance().isValid(EmailAddressejTextField1.getText());
        
        if( Validate== false)
        {
              JOptionPane.showMessageDialog(null, "Please enter a valid E-Mail address!","ERROR", JOptionPane.ERROR_MESSAGE); 
        }
        else
        {
             if(jCheckBox1.isSelected()){  
       DBHandler mydbhandler= new DBHandler();
       String password = new String(PasswordjPasswordField2.getPassword());
       String confirmationPassword= new String(ConfirmjPasswordField1.getPassword());
       Encryption enc= new Encryption(password);
       String hash= enc.HaschCode();
       boolean createUser= true;
       
       ResultSet rsForUser= mydbhandler.Selectdata("paymentUsers", "usernamep",  UsernamejTextField1.getText());
       ResultSet rsForEmail= mydbhandler.Selectdata("paymentUsers", "emailp",  EmailAddressejTextField1.getText());

       if (mydbhandler.checkstatmentExsist(rsForUser))
       {
            
            JOptionPane.showMessageDialog(null, "Username is already exists","ERROR", JOptionPane.ERROR_MESSAGE);
            createUser=false;
            
        
       }
        if (mydbhandler.checkstatmentExsist(rsForEmail))
       {
            JOptionPane.showMessageDialog(null, "E-Mail is already exists","ERROR", JOptionPane.ERROR_MESSAGE);
            createUser=false;
       }
       //System.out.println(password+ " "+confirmationPassword);
       if(!password.equals(confirmationPassword))
        {
           JOptionPane.showMessageDialog(null, "Password and Password Confirmation are not equal!","ERROR", JOptionPane.ERROR_MESSAGE);
            createUser=false;
        }
       
       //get information to insert them in DB newUser
       
       String firstname= FirstnamejTextField1.getText();
        String lastname= LastnamejTextField1.getText();
        String username1= UsernamejTextField1.getText();
        String email= EmailAddressejTextField1.getText();
        
        if( createUser)
        {
        mydbhandler.newUser("users",firstname, lastname, username1,hash,email);
        JOptionPane.showMessageDialog(null, "Registration complete","INFO", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        new Login2(username1,id,fromcity,tocity,Datum,departureTime,arriveTime,price,seat,seatdb).setVisible(true);
        }
         }
     else{
    JOptionPane.showMessageDialog(null,"Please confirm our request");

     }
        }
    }//GEN-LAST:event_RegisterjButton1ActionPerformed

    private void PasswordjPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordjPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordjPasswordField2ActionPerformed

    private void ConfirmjPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmjPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmjPasswordField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmjPasswordField1;
    private javax.swing.JTextField EmailAddressejTextField1;
    private javax.swing.JLabel EmailjLabel2;
    private javax.swing.JLabel FirstnamejLabel1;
    private javax.swing.JTextField FirstnamejTextField1;
    private javax.swing.JLabel LastnamejLabel1;
    private javax.swing.JTextField LastnamejTextField1;
    private javax.swing.JLabel Password1jLabel1;
    private javax.swing.JLabel PasswordjLabel2;
    private javax.swing.JPasswordField PasswordjPasswordField2;
    private javax.swing.JButton RegisterjButton1;
    private javax.swing.JLabel RegisterjLabel1;
    private javax.swing.JLabel UsernamejLabel1;
    private javax.swing.JTextField UsernamejTextField1;
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables
}
