/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.luxbus.frontend;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author haith
 */
public class StartWindowAfterLoginAdmin extends javax.swing.JFrame { 
    /**
     * Creates new form StartWindowAfterLogin
     */
    String username;
    public StartWindowAfterLoginAdmin(String username) {
         this.username=username;
        System.out.println("username is ->>>"+username);
        initComponents();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 
        Date date = new Date();
        choosenDeparture.setDate(date);
         bxTakeABike.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInFrame = new javax.swing.JPanel();
        labelfrom = new javax.swing.JLabel();
        labelTo = new javax.swing.JLabel();
        swapButton = new javax.swing.JButton();
        labelDeparture = new javax.swing.JLabel();
        labelReserveSeat = new javax.swing.JLabel();
        bxTakeABike = new javax.swing.JCheckBox();
        resetButton = new javax.swing.JButton();
        validateButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        comboBoxSelectClass = new javax.swing.JComboBox<>();
        labelSelectClass = new javax.swing.JLabel();
        choosenDeparture = new com.toedter.calendar.JDateChooser();
        chooseSeat = new com.toedter.components.JSpinField();
        textFieldFrom = new javax.swing.JComboBox<>();
        textFieldTo = new javax.swing.JComboBox<>();
        userManagmentButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LuxcoinLabel = new javax.swing.JLabel();
        paymentLoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome in LUXBUS");

        panelInFrame.setBackground(new java.awt.Color(204, 255, 204));

        labelfrom.setText("From");

        labelTo.setText("To");

        swapButton.setText("Swap");
        swapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapButtonActionPerformed(evt);
            }
        });

        labelDeparture.setText("Departure");

        labelReserveSeat.setText("Reserve seat:");

        bxTakeABike.setText("I certify that I have received a Corona vaccination or ");
        bxTakeABike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxTakeABikeActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        validateButton.setText("Search");
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        comboBoxSelectClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy class", "First class( +40 € )" }));
        comboBoxSelectClass.setToolTipText("");
        comboBoxSelectClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSelectClassActionPerformed(evt);
            }
        });

        labelSelectClass.setText("Select class");

        chooseSeat.setMaximum(80);
        chooseSeat.setMinimum(1);
        chooseSeat.setValue(1);

        textFieldFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frankfurt am Main", "Berlin", "Köln", "Hannover", "Hamburg", "München", "Leipzig", "Stuttgart" }));
        textFieldFrom.setToolTipText("");
        textFieldFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFromActionPerformed(evt);
            }
        });

        textFieldTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Berlin", "Frankfurt am Main", "Köln", "Hannover", "Hamburg", "München", "Leipzig", "Stuttgart" }));
        textFieldTo.setDoubleBuffered(true);
        textFieldTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldToActionPerformed(evt);
            }
        });

        userManagmentButton.setText("User managment");
        userManagmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagmentButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Travels managment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("have a negative Corona test of no longer than 24 hours.");

        javax.swing.GroupLayout panelInFrameLayout = new javax.swing.GroupLayout(panelInFrame);
        panelInFrame.setLayout(panelInFrameLayout);
        panelInFrameLayout.setHorizontalGroup(
            panelInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInFrameLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(userManagmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetButton)
                        .addGap(18, 18, 18)
                        .addComponent(validateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInFrameLayout.createSequentialGroup()
                        .addGroup(panelInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInFrameLayout.createSequentialGroup()
                                .addComponent(labelSelectClass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInFrameLayout.createSequentialGroup()
                                .addGroup(panelInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboBoxSelectClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelReserveSeat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelfrom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDeparture, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choosenDeparture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textFieldFrom, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(swapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(191, 191, 191)))
                        .addGroup(panelInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInFrameLayout.createSequentialGroup()
                        .addGroup(panelInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bxTakeABike)
                            .addGroup(panelInFrameLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelInFrameLayout.setVerticalGroup(
            panelInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInFrameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelfrom)
                    .addComponent(labelTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(swapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(labelDeparture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choosenDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(labelReserveSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSelectClass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxSelectClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bxTakeABike)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panelInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(validateButton)
                    .addComponent(quitButton)
                    .addComponent(userManagmentButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        LuxcoinLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        LuxcoinLabel.setForeground(new java.awt.Color(102, 255, 0));
        LuxcoinLabel.setText("Luxcoin");

        paymentLoginButton.setText("Login ");
        paymentLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentLoginButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("sign in or sign up by Luxcoin and make your payment more simple  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LuxcoinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(156, 156, 156)
                .addComponent(paymentLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LuxcoinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentLoginButton)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void swapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swapButtonActionPerformed
        String swapping = textFieldFrom.getSelectedItem().toString();
        textFieldFrom.setSelectedItem(textFieldTo.getSelectedItem().toString());//setText(textFieldTo.getText());
        textFieldTo.setSelectedItem(swapping);
    }//GEN-LAST:event_swapButtonActionPerformed

    private void bxTakeABikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxTakeABikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bxTakeABikeActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // Noch sicher stellen 
        bxTakeABike.setSelected(false);
        
// Reset choosen Set 
        chooseSeat.setMaximum(80);
        chooseSeat.setMinimum(1);
        chooseSeat.setValue(1);
        
// Reset choosen Departure
        choosenDeparture.setDate(null);

        
        comboBoxSelectClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economec", "First class" }));
        
// Reset Textfield From and To
        textFieldFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frankfurt am Main", "Berlin", "München", "Stuttgart" }));
        textFieldFrom.setToolTipText("");
        textFieldFrom.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFromActionPerformed(evt);
            }
        });
        textFieldTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frankfurt am Main", "Berlin", "München", "Stuttgart" }));
        textFieldTo.setSelectedIndex(1);
        textFieldTo.setDoubleBuffered(true);
        textFieldTo.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldToActionPerformed(evt);
            }
        });
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
       
    if(bxTakeABike.isSelected()) {
    String From=(String) textFieldFrom.getSelectedItem();
    String To=(String) textFieldTo.getSelectedItem();
    Date datum= choosenDeparture.getDate();
    System.out.println("datum---->"+datum);
    int year=datum.getYear()+1900;
    int day=datum.getDate();
    int month=datum.getMonth()+1;

      String date=year+"-"+month+"-"+day;
        System.out.println("datum---->"+date);
        int seat=chooseSeat.getValue();
               String classart=(String) comboBoxSelectClass.getSelectedItem();
                System.out.println("class --> "+classart);
        new result(username,From,To,date,seat,classart).setVisible(true);
 }
         else{
                 JOptionPane.showMessageDialog(null,"Please confirm our request");

         }
    }//GEN-LAST:event_validateButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void comboBoxSelectClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSelectClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSelectClassActionPerformed

    private void textFieldFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFromActionPerformed

    private void textFieldToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldToActionPerformed
        
    }//GEN-LAST:event_textFieldToActionPerformed

    private void paymentLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentLoginButtonActionPerformed
        new PaymentLogin().setVisible(true);
    }//GEN-LAST:event_paymentLoginButtonActionPerformed

    private void userManagmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagmentButtonActionPerformed
        Usermanagement start = new Usermanagement();
        start.setVisible(true);
    }//GEN-LAST:event_userManagmentButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           Travelsmanagement start = new Travelsmanagement();
        start.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LuxcoinLabel;
    private javax.swing.JCheckBox bxTakeABike;
    private com.toedter.components.JSpinField chooseSeat;
    private com.toedter.calendar.JDateChooser choosenDeparture;
    private javax.swing.JComboBox<String> comboBoxSelectClass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelDeparture;
    private javax.swing.JLabel labelReserveSeat;
    private javax.swing.JLabel labelSelectClass;
    private javax.swing.JLabel labelTo;
    private javax.swing.JLabel labelfrom;
    private javax.swing.JPanel panelInFrame;
    private javax.swing.JButton paymentLoginButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton swapButton;
    private javax.swing.JComboBox<String> textFieldFrom;
    private javax.swing.JComboBox<String> textFieldTo;
    private javax.swing.JButton userManagmentButton;
    private javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables

      private javax.swing.JButton admin;
}
