/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.luxbus.frontend;

import de.frauas.luxbus.backend.DBHandler;
import de.frauas.luxbus.backend.Encryption;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.apache.commons.validator.routines.EmailValidator;

/**
 *
 * @author haith
 */
public class Updating extends javax.swing.JFrame {
String username2;
    /**
     * Creates new form CreateAccountPayment
     * @param username2
     */
    public Updating(String username2) {
        this.username2 = username2;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        luxpaymentCreateAccountLabel = new javax.swing.JLabel();
        UserNamePaymentLabel = new javax.swing.JLabel();
        firstNamePaymentLable = new javax.swing.JLabel();
        lastNamePaymentLabel = new javax.swing.JLabel();
        AddressPaymentLabel = new javax.swing.JLabel();
        eMailPaymentLabel = new javax.swing.JLabel();
        rewritePasswordPaymentLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        usernamePaymentTextField = new javax.swing.JTextField();
        firstNamePaymentTextField = new javax.swing.JTextField();
        lastNamePaymentTextField = new javax.swing.JTextField();
        addressPaymentTextField = new javax.swing.JTextField();
        eMailPaymentTextField = new javax.swing.JTextField();
        PasswordPaymentTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign up LUXPAYMENT");

        luxpaymentCreateAccountLabel.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        luxpaymentCreateAccountLabel.setText("Luxpayment ");

        UserNamePaymentLabel.setText("Username:");

        firstNamePaymentLable.setText("First name:");

        lastNamePaymentLabel.setText("Last name:");

        AddressPaymentLabel.setText("Address:");

        eMailPaymentLabel.setText("E-Mail Address:");

        rewritePasswordPaymentLabel.setText("Password");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        usernamePaymentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamePaymentTextFieldActionPerformed(evt);
            }
        });

        firstNamePaymentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNamePaymentTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Hello "+username2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(updateButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(UserNamePaymentLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rewritePasswordPaymentLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eMailPaymentLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddressPaymentLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNamePaymentLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstNamePaymentLable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(luxpaymentCreateAccountLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(eMailPaymentTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(addressPaymentTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastNamePaymentTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstNamePaymentTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernamePaymentTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PasswordPaymentTextField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(luxpaymentCreateAccountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNamePaymentLabel)
                    .addComponent(usernamePaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNamePaymentLable)
                    .addComponent(firstNamePaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNamePaymentLabel)
                    .addComponent(lastNamePaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressPaymentLabel)
                    .addComponent(addressPaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMailPaymentLabel)
                    .addComponent(eMailPaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rewritePasswordPaymentLabel)
                    .addComponent(PasswordPaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNamePaymentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNamePaymentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNamePaymentTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        
        boolean Validate= EmailValidator.getInstance().isValid(eMailPaymentTextField.getText());
        
        if( Validate== false)
        {
              JOptionPane.showMessageDialog(null, "Please enter a valid E-Mail address!","ERROR", JOptionPane.ERROR_MESSAGE); 
        }
        else
        {
            String password = PasswordPaymentTextField.getText();
            String confirmationPassword= PasswordPaymentTextField.getText();
            Encryption enc= new Encryption(password);
            String hash= enc.HaschCode();
            DBHandler mydbhandler= new DBHandler();
            
            boolean updateUser= true;
       
       //System.out.println(password+ " "+confirmationPassword);
            if(!password.equals(confirmationPassword))
            {
                JOptionPane.showMessageDialog(null, "Password and Password Confirmation are not equal!","ERROR", JOptionPane.ERROR_MESSAGE);
                updateUser=false;
            }
       
            //get information to insert them in DB newUser
       
            String firstname= firstNamePaymentTextField.getText();
            String lastname= lastNamePaymentTextField.getText();
            String username= usernamePaymentTextField.getText();
            String email= eMailPaymentTextField.getText();
            String address = addressPaymentTextField.getText();
    //        String dob = ((JTextField)choosenDeparture.getDateEditor().getUiComponent()).getText();

                //jDateChooser1.get;
        
            if( updateUser){
                mydbhandler.UpdatePayment(firstname, lastname, username, hash, address,/* dob,*/ email, username2);
                JOptionPane.showMessageDialog(null, "Successfully updated","INFO", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void usernamePaymentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamePaymentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamePaymentTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressPaymentLabel;
    public static javax.swing.JPasswordField PasswordPaymentTextField;
    private javax.swing.JLabel UserNamePaymentLabel;
    public static javax.swing.JTextField addressPaymentTextField;
    private javax.swing.JLabel eMailPaymentLabel;
    public static javax.swing.JTextField eMailPaymentTextField;
    private javax.swing.JLabel firstNamePaymentLable;
    public javax.swing.JTextField firstNamePaymentTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNamePaymentLabel;
    public static javax.swing.JTextField lastNamePaymentTextField;
    private javax.swing.JLabel luxpaymentCreateAccountLabel;
    private javax.swing.JLabel rewritePasswordPaymentLabel;
    public static javax.swing.JButton updateButton;
    public static javax.swing.JTextField usernamePaymentTextField;
    // End of variables declaration//GEN-END:variables

    //For PaymentStartWindow changing
    
    public void SetDate(String userN,String firstname, String lastname,String Pass,String email, String address,String date){
            usernamePaymentTextField.setText(userN);
            eMailPaymentTextField.setText(Pass);
            PasswordPaymentTextField.setText(Pass);
            lastNamePaymentTextField.setText(lastname);
            firstNamePaymentTextField.setText(firstname);
            eMailPaymentTextField.setText(email);
            addressPaymentTextField.setText(address);
    }
}
